# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c335a6e05c20149efb63d11940d3864813be11f38f90edcaed82cade94aaca2e44f14ec87af9d534d3f9b85e3da956d613cb03eebca0f7b20a4c2cb24e2030d3

test:
  secret_key_base: 3b6d14cc6d28d443c32b2170f86828de20c759ef2b81a4bf82847893a54d138eafee1c5fb427573507181db57ac32c5e4a66091c13656b9b656d3df30f7b4d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
